### ISSUE TITLE
verb "SAY" veridical?

### ISSUE THREAD

**Issue by vcvpaiva** [kkalouli/GKR_semantic_parser#1]
Tried the sentence "She said that the boy is tall" and got that the verb say is veridical, why?

**Comment by kkalouli** [comment]
Based on the work "Integrating Deep Linguistic Features in Factuality Prediction over Unified Datasets" by Stanovsky, Eckle-Kohler, Puzikov, Dagan and Gurevych (2017) (which in turn is based on Lauri's Kartunnen work on implicatives and factives (1971, 2012)) the verb "say that" has the signature "P_U", i.e. has positive polarity in affirmative contexts and unknown polarity in negative contexts. Thus, in this affirmative context it has positive polarity and thus the embedded clause "boy is tall" is veridical in it.

**Comment by vcvpaiva** [comment]
Many thanks for the information! but I think this might be a bug on their data. I can believe no one goes around saying false things about what people didn't say (perhaps) but to say that what people say is generally true seems to me wrong. actually pragmatically the fact that you bring your source into the sentence might indicate that you don't believe it yourself. it needs checking, I think. will ask Dick and Lauri about it.

**Comment by kkalouli** [comment]
Yes, this is indeed a debatable question whether reported speech should be assumed true or not. There is in fact a good bit of discussion in the papers by Zaenen, Kartunnen, Crouch (2005) and Manning (2006) and then again Crouch, Kartunnen, Zaenen (2006). Also, Dagan tries to pin down this issue in RTE1 by saying that strict entailment cannot be used for real-world applications by giving the example: 
Hypothesis: According to the Encyclopedia Britannica, Indonesia is the largest archipelagic nation in the world, consisting of 13,670 islands. 
Text: 13,670 islands make up Indonesia.
marked as FOLLOWS. (RTE1, ID:605)

I think, for the purposes of the human-like inference that GKR is aiming at, we need this kind of looseness here, to allow factives like say, report, etc. to be veridical but distinguish them for example from words of belief like believe which would give rise to averidical contexts.
