### ISSUE TITLE
source of the HP suite

### ISSUE THREAD

**Issue by arademaker** [kkalouli/GKR_semantic_parser#2]
Can you provide a link for the source of the HP test suite HP_testsuite_version_for_evaluating_GKR.txt ? 

Is it related to http://moin.delph-in.net/MatrixMrsTestSuite?

**Comment by kkalouli** [comment]
Hi,
the HP test suite can be found here: https://w3.ual.es/~nperdu/hpsuite.htm
The version used to evaluate GKR is slightly shorter because some of the phenomena of the test suite had not yet been implemented in GKR at the time of publishing of this work (and some still aren't)
